#!/usr/bin/env bash
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fail() { echo "FAIL: $*" >&2; exit 1; }
pass() { echo "PASS: $*"; }

for script in "${HERE}"/*.sh "${HERE}/openbao/materialize-zitadel.sh"; do bash -n "${script}" || fail "bash syntax: ${script}"; done
python3 -m py_compile "${HERE}/secret_scan.py" "${HERE}/failure_diagnostics.py" || fail "secret scanner syntax"
pass "all shell scripts parse"
awk -v current_load=0.5 'BEGIN {exit !(current_load <= 2.5)}' || fail "GNU awk load preflight"
pass "GNU awk host-load preflight parses"
grep -q 'cached exact image architecture mismatch' "${HERE}/preflight.sh" || fail "cached dependency architecture check"
grep -q 'ZITADEL-specific image residue exists' "${HERE}/preflight.sh" || fail "ZITADEL image residue hard stop"
pass "shared exact dependency cache is validated without cross-project deletion"

rendered="$(docker compose -p tanaghom-zitadel-dev-test -f "${HERE}/docker-compose.yml" config --format json)"
[[ "$(jq -r '.services | keys | sort | join(" ")' <<<"${rendered}")" == "caddy postgres zitadel-api zitadel-login" ]] || fail "service allowlist"
[[ "$(jq -r '.networks.iam.name' <<<"${rendered}")" == tanaghom-iam-dev ]] || fail "network name"
[[ "$(jq -r '.services.caddy.ports[0].host_ip + ":" + (.services.caddy.ports[0].published|tostring)' <<<"${rendered}")" == 127.0.0.1:18210 ]] || fail "loopback publication"
[[ "$(jq -r '[.services[] | .ports // [] | length] | add' <<<"${rendered}")" == 1 ]] || fail "unexpected published port"

[[ "$(jq -r '.services["zitadel-api"].deploy.resources.limits.cpus' <<<"${rendered}")" == 1 ]] || fail "API CPU limit"
[[ "$(jq -r '.services["zitadel-api"].deploy.resources.limits.memory' <<<"${rendered}")" == 805306368 ]] || fail "API memory limit"
[[ "$(jq -r '.services["zitadel-login"].deploy.resources.limits.memory' <<<"${rendered}")" == 402653184 ]] || fail "Login memory limit"
[[ "$(jq -r '.services.postgres.deploy.resources.limits.memory' <<<"${rendered}")" == 536870912 ]] || fail "PostgreSQL memory limit"
[[ "$(jq -r '.services.caddy.deploy.resources.limits.memory' <<<"${rendered}")" == 134217728 ]] || fail "Caddy memory limit"
[[ "$(jq -r '.services["zitadel-api"].user' <<<"${rendered}")" == 0 ]] || fail "API root custody reader"
[[ "$(jq -r '.services["zitadel-login"].user' <<<"${rendered}")" == 0 ]] || fail "Login PAT custody reader"
pass "topology, exposure, and resource ceilings render exactly"

grep -q -- '--masterkeyFile' "${HERE}/docker-compose.yml" || fail "masterkey file seam missing"
[[ "$(grep -c '/run/tanaghom-zitadel/current/' "${HERE}/docker-compose.yml")" == 4 ]] || fail "atomic generation paths"
grep -q 'POSTGRES_PASSWORD_FILE:' "${HERE}/docker-compose.yml" || fail "PostgreSQL password file seam missing"
grep -q 'ZITADEL_SERVICE_USER_TOKEN_FILE:' "${HERE}/docker-compose.yml" || fail "Login token file seam missing"
grep -Eq 'POSTGRES_PASSWORD:[[:space:]]' "${HERE}/docker-compose.yml" && fail "direct PostgreSQL password environment"
grep -Eq 'ZITADEL_MASTERKEY:[[:space:]]' "${HERE}/docker-compose.yml" && fail "direct masterkey environment"
grep -Eq 'docker\.sock|privileged:[[:space:]]*true|network_mode:[[:space:]]*host|0\.0\.0\.0:' "${HERE}/docker-compose.yml" && fail "prohibited Compose capability"
grep -Eq 'build:|env_file:|\.env' "${HERE}/docker-compose.yml" && fail "build or env-file seam present"
grep -Eq 'python3[^|]*(\$\{value\}|\$\{masterkey\}|\$\{postgres_password\}|\$\{admin_password\})' \
  "${HERE}/provision.sh" "${HERE}/openbao/materialize-zitadel.sh" && fail "secret value passed in process argv"
pass "secret seams are file-only and prohibited capabilities are absent"

grep -q 'mv -Tf "${OUT_DIR}/.current.new" "${OUT_DIR}/current"' "${HERE}/openbao/materialize-zitadel.sh" || fail "atomic current activation"
grep -q 'chmod 0500 "${generation}"' "${HERE}/openbao/materialize-zitadel.sh" || fail "generation directory mode"
[[ "$(tail -n 7 "${HERE}/openbao/materialize-zitadel.sh" | grep -c 'mv -Tf')" == 1 ]] || fail "activation is not the final fallible operation"
grep -q 'docker.*inspect' "${HERE}/secret_scan.py" || fail "inspect byte scan"
grep -q 'docker.*logs' "${HERE}/secret_scan.py" || fail "log byte scan"
grep -q 'login-client.pat' "${HERE}/secret_scan.py" || fail "Login PAT byte source"
grep -q 'evidence_root.rglob' "${HERE}/secret_scan.py" || fail "retained evidence byte scan"
grep -q 'secret_scan.py.*predeploy' "${HERE}/deploy.sh" || fail "predeploy secret scan"
grep -q 'secret_scan.py.*runtime' "${HERE}/verify.sh" || fail "runtime secret scan"
[[ "$(grep -c 'secret_scan.py.*runtime' "${HERE}/verify.sh")" == 2 ]] || fail "post-observation secret rescan"
grep -q 'failure_diagnostics.py' "${HERE}/deploy.sh" || fail "failure diagnostics missing"
grep -q 'any(secret in payload' "${HERE}/failure_diagnostics.py" || fail "failure diagnostic exact-byte scan missing"
grep -q 'login-client.pat' "${HERE}/failure_diagnostics.py" || fail "failure diagnostic PAT scan missing"
grep -q 'LOG_PATTERNS' "${HERE}/failure_diagnostics.py" || fail "fixed-vocabulary diagnostic classifier missing"
grep -q 'docker.*, "ps".*, "--no-trunc"' "${HERE}/failure_diagnostics.py" || fail "full candidate container identity missing"
grep -q 'candidate service label is outside the allowlist' "${HERE}/failure_diagnostics.py" || fail "failure diagnostic service allowlist missing"
grep -q 'raw_logs_retained=false' "${HERE}/failure_diagnostics.py" || fail "raw-log non-retention verdict missing"
grep -q 'logs.txt' "${HERE}/failure_diagnostics.py" && fail "raw log retention path present"
grep -q 'failure_diagnostics.py reset-diagnostic.sh' "${HERE}/stage.sh" || fail "diagnostic controls missing from staged allowlist"
pass "secret generations and exact-byte evidence scans are enforced"

grep -q 'retries: 30' "${HERE}/docker-compose.yml" || fail "bounded bootstrap health budget"
grep -Fq 'test: ["CMD", "/app/zitadel", "ready", "--config", "/etc/zitadel/zitadel-config.yaml"]' "${HERE}/docker-compose.yml" \
  || fail "ZITADEL readiness probe does not load the committed HTTP/TLS config"
grep -q -- '--wait-timeout 420' "${HERE}/deploy.sh" || fail "bounded Compose bootstrap wait"
pass "resource-capped bootstrap has one finite budget and a config-aligned readiness probe"

[[ "$(grep -c '^path ' "${HERE}/openbao/zitadel-policy.hcl")" == 3 ]] || fail "policy path count"
grep -q 'capabilities = \["read"\]' "${HERE}/openbao/zitadel-policy.hcl" || fail "read-only policy"
grep -Eq 'create|update|delete|list|sudo' "${HERE}/openbao/zitadel-policy.hcl" && fail "policy exceeds read-only capability"
grep -q '^RuntimeDirectory=tanaghom-zitadel$' "${HERE}/openbao/tanaghom-zitadel-secrets.service" || fail "runtime directory missing"
grep -q '^RuntimeDirectoryMode=0500$' "${HERE}/openbao/tanaghom-zitadel-secrets.service" || fail "runtime directory mode"
grep -q '^ReadWritePaths=/run/tanaghom-zitadel$' "${HERE}/openbao/tanaghom-zitadel-secrets.service" || fail "systemd write allowlist"
grep -q '^User=root$' "${HERE}/openbao/tanaghom-zitadel-secrets.service" || fail "materializer identity"
pass "OpenBao policy and systemd sandbox are bounded"

[[ "$(grep -c '^[^#].*|' "${HERE}/provenance.lock")" == 4 ]] || fail "provenance record count"
while IFS='|' read -r _name _tag index child source; do
  [[ "${index}" =~ ^sha256:[0-9a-f]{64}$ && "${child}" =~ ^sha256:[0-9a-f]{64}$ && "${source}" == https://* ]] || fail "provenance record grammar"
done < "${HERE}/provenance.lock"
grep -q 'ExternalDomain: iam.localhost' "${HERE}/zitadel-config.yaml" || fail "external domain"
grep -q 'ExternalPort: 13210' "${HERE}/zitadel-config.yaml" || fail "external port"
grep -q 'ExternalSecure: false' "${HERE}/zitadel-config.yaml" || fail "developer HTTP posture"
grep -q 'BaseURI: http://iam.localhost:13210/ui/v2/login/' "${HERE}/zitadel-config.yaml" || fail "Login V2 base URI"
pass "immutable provenance and issuer configuration are explicit"

grep -q 'down --remove-orphans' "${HERE}/rollback.sh" || fail "bounded Compose rollback missing"
for script in "${HERE}/preflight.sh" "${HERE}/provision.sh" "${HERE}/deploy.sh" "${HERE}/verify.sh" "${HERE}/rollback.sh"; do
  grep -q 'docker .*prune' "${script}" && fail "broad Docker prune present"
done
grep -qE 'down[[:space:]].*-v([[:space:]]|$)' "${HERE}/rollback.sh" && fail "rollback would delete PostgreSQL volume"
grep -q 'operator raft snapshot restore' "${HERE}/rollback.sh" && fail "automatic full snapshot restore present"
grep -q 'docker volume rm "${LOGIN_VOLUME}"' "${HERE}/rollback.sh" || fail "Login PAT volume removal missing"
grep -q 'docker volume inspect "${POSTGRES_VOLUME}"' "${HERE}/rollback.sh" || fail "PostgreSQL volume preservation proof missing"
grep -q 'com.docker.compose.project' "${HERE}/reset-diagnostic.sh" || fail "diagnostic reset project-label guard missing"
grep -q 'com.docker.compose.volume' "${HERE}/reset-diagnostic.sh" || fail "diagnostic reset volume-label guard missing"
grep -q 'docker volume rm "${POSTGRES_VOLUME}"' "${HERE}/reset-diagnostic.sh" || fail "exact diagnostic reset missing"
grep -Eq 'docker (system|image|container|network|volume) prune' "${HERE}/reset-diagnostic.sh" && fail "diagnostic reset contains broad prune"
grep -q 'pre-change OpenBao snapshot was not preserved' "${HERE}/rollback.sh" || fail "snapshot preservation proof missing"
grep -q 'preserved.*identity drifted' "${HERE}/rollback.sh" || fail "workload identity proof missing"
grep -q 'docker network inspect' "${HERE}/rollback.sh" || fail "network identity proof missing"
grep -q 'docker network inspect' "${HERE}/verify.sh" || fail "verification network identity proof missing"
grep -q 'OpenBao KV residue remains' "${HERE}/rollback.sh" || fail "OpenBao absence proof missing"
grep -q 'candidate runtime residue remains' "${HERE}/rollback.sh" || fail "runtime absence proof missing"
grep -q 'candidate systemd unit file remains' "${HERE}/rollback.sh" || fail "systemd absence proof missing"
grep -Fq '|| true' "${HERE}/rollback.sh" && fail "rollback suppresses an exact failure"
grep -q 'rollback.sh' "${HERE}/deploy.sh" || fail "deploy compensation missing"
grep -q 'rollback.sh' "${HERE}/verify.sh" || fail "verify compensation missing"
pass "rollback is journal-bounded and proves removal, preservation, and identity postconditions"

echo "PACKAGING_VERDICT=PASS"
